[Interface]
PrivateKey = 3dBChRaZ68bTpG961GZmOu7mxeRYZbRIFaKX6iL93Hk=
Address = 10.0.0.1/32
DNS = 10.0.0.53

[Peer]
PublicKey = r6SKFQsMv8uSn82zFOqOuW0ZCq/QWguTpdVmjhgbIlU=
AllowedIPs = 0.0.0.0/0
Endpoint = 172.27.64.1:51820
PersistentKeepalive = 25
